universe = vanilla

# executable must be in submission folder
executable = bash_script.sh
# list of arguments to executable (empty is accepted)
arguments =

# ask to transfer files (YES/NO) whenever the filesystem is NOT shared
should_transfer_files = YES
# list input files to transfer, eg transfer_input_files=file1,file2,file3
transfer_input_files = py_script.py
# list the ONLY output files to transfer, eg ttransfer_output_files=file1,file2,file3
# NB: if line is NOT found, then all generated/updated files are transferred back
# transfer_output_files = 
when_to_transfer_output = ON_EXIT

# run job as owner, such that you can ssh to job
run_as_owner = TRUE

log = htcondor_$(ClusterId).log
output = htcondor_$(ClusterId)_$(ProcId).out
error = htcondor_$(ClusterId)_$(ProcId).err

request_cpus = 5
request_disk = 200MB
request_memory = 2GB

# GPU requests
request_gpus = 1
# requirements = (Target.CUDADeviceMemoryMb >= 8000)

JobBatchName = "python_testGPU_01"

# submit 1 instances
queue 5