# override default value of EXECUTE to a dedicated filesystem
# NB: please remember to set access rights and ownerships as
#     the original folder:
# root@svpvclus02:/etc/condor/config.d# condor_config_val EXECUTE
# /var/lib/condor/execute
# root@svpvclus02:/etc/condor/config.d# ll /var/lib/condor/execute/
# total 8
# drwxr-xr-x 2 condor condor 4096 May 11 08:54 ./
# drwxr-xr-x 3 condor root   4096 May 11 08:54 ../
EXECUTE = /htc/condor/execute
