#
# root@svpvclus01:/etc/condor/config.d# condor_config_val -dump UID_DOMAIN
# # Configuration from machine: svpvclus01
# 
# # Parameters with names that match UID_DOMAIN:
# SOFT_UID_DOMAIN = 
# TRUST_LOCAL_UID_DOMAIN = true
# TRUST_UID_DOMAIN = 
# UID_DOMAIN = $(FULL_HOSTNAME)
# # Contributing configuration file(s):
# #	/etc/condor/condor_config
# #	/etc/condor/config.d/00-security
# #	/etc/condor/config.d/01-central-manager.config
# #	/etc/condor/config.d/02-execute.config
# #	/etc/condor/config.d/03-submit.config
# #	/etc/condor/config.d/49-OS-reservation.conf
# #	/etc/condor/config.d/50-local.conf
# #	/etc/condor/condor_config.local
#
# forcing domain to be that of the cluster
UID_DOMAIN = cnao.group
