CONDOR_HOST = svpvclus01.cnao.group

# For details, run condor_config_val use role:get_htcondor_central_manager
use role:get_htcondor_central_manager

# For details, run condor_config_val use role:get_htcondor_execute
use role:get_htcondor_execute

# For details, run condor_config_val use role:get_htcondor_submit
use role:get_htcondor_submit
