# override default value of SPOOL to a dedicated filesystem
# NB: please remember to set access rights and ownerships as
#     the original folder:
# root@svpvclus01:/htc/condor/execute# condor_config_val SPOOL
# /var/spool/condor
# root@svpvclus01:/htc/condor/execute# ll /var/spool/condor
# total 108
# drwxr-xr-x 3 condor condor  4096 Apr 28 13:44 ./
# drwxr-xr-x 6 root   root    4096 Apr 28 11:33 ../
# -rw-r--r-- 1 condor condor   227 Apr 28 13:19 .schedd_address
# -rw-r--r-- 1 condor condor   176 Apr 28 13:19 .schedd_address.super
# -rw-r--r-- 1 condor condor  6163 Apr 28 13:44 .schedd_classad
# -rw------- 1 condor condor  5427 Apr 28 13:44 Accountantnew.log
# -rw------- 1 condor condor   204 Apr 28 13:19 job_queue.log
# -rw------- 1 condor condor   121 Apr 28 11:44 job_queue.log.1
# drwxr-xr-x 2 condor condor  4096 Apr 28 11:33 local_univ_execute/
# -rw-r--r-- 1 condor condor 55635 Apr 28 13:34 schedd_daemon_history
# -rw-r--r-- 1 condor condor    59 Apr 28 11:44 spool_version
SPOOL = /mnt/san_data/condor/spool
# ...but keep the job queue log in the default installation path
JOB_QUEUE_LOG = /var/spool/condor/job_queue.log

# override default value of EXECUTE to a dedicated filesystem
# NB: please remember to set access rights and ownerships as
#     the original folder:
# root@svpvclus01:/htc/condor/execute# condor_config_val EXECUTE
# /var/lib/condor/execute
# root@svpvclus01:/htc/condor/execute# ll /var/lib/condor/execute
# total 8
# drwxr-xr-x 2 condor condor 4096 Apr 28 13:19 ./
# drwxr-xr-x 3 condor condor 4096 Apr 28 11:33 ../
EXECUTE = /htc/condor/execute
